- name: Deploy Fotobox
  hosts: all
  tasks:

    # - name: Update System (can take a while)
    #   become: true
    #   ansible.builtin.apt:
    #     update_cache: true
    #     upgrade: full
    #     autoremove: true
    #   register: apt

    # - name: Reboot on package changes
    #   become: true
    #   ansible.builtin.reboot:
    #     reboot_timeout: 300
    #   when: apt.changed # noqa: no-handler

    - name: Stop old Fotobox
      ansible.builtin.debug:

    - name: Sync directory
      ansible.posix.synchronize:
        src: .
        dest: .
        delete: true
        recursive: true
        rsync_opts:
          - "--exclude .git"
          - "--exclude .ansible"
          - "--exclude .venv"
          - "--exclude .vscode"
          - "--exclude '*.pyc'"

    # normally done with ansible.builtin.pip, but that seems broken
    - name: Create venv
      ansible.builtin.command: python3 -m venv .venv
      args:
        chdir: fotobox
        creates: fotobox/.venv/bin/activate
      register: venv

    - name: Install venv packages # noqa: no-changed-when
      ansible.builtin.command: ./.venv/bin/pip install -r requirements.txt
      args:
        chdir: fotobox
      when: venv.changed # noqa: no-handler

    - name: Create autostart
      ansible.builtin.debug:

    - name: Invoke
      ansible.builtin.debug:
